baseURL = "https://willcornwell.org/"
languageCode = "en-us"
title = "Will Cornwell"
theme = "PaperMod"
publishDir = "public"

[pagination]
  pagerSize = 5

pygmentsUseClasses = true
pygmentsCodeFences = true
defaultContentLanguage = "en"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = "Will Cornwell"
  description = "Ecologist | Researcher | Lecturer"
  defaultTheme = "auto"
  disableThemeToggle = false
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = false
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  hideFooter = true
  disableScrollToTop = false
  homeInfoParams = { Title = "Will Cornwell", Content = "Ecologist | Researcher | Lecturer. This site is a work in progress." }

  [params.profileMode]
    enabled = true
    title = "Will Cornwell"
    subtitle = "Ecological Data Science"
    imageUrl = "images/will.jpg"
    imageTitle = "Photo of Will Cornwell"
    imageWidth = 120
    imageHeight = 120

  [params.assets]
    customCSS = ["css/lightbox.css"]
    customJS  = ["js/lightbox.js"]

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/wcornwell"

[[params.socialIcons]]
  name = "email"
  url = "mailto:w.cornwell@unsw.edu.au"

[[params.socialIcons]]
  name = "orcid"
  url = "https://orcid.org/0000-0003-4080-4073"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/will-cornwell/"

[[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/willcornwell_nature/"

[[params.socialIcons]]
  name = "YouTube"
  url = "https://www.youtube.com/@wily98988"

[menu]

[[menu.main]]
  name = "Bio"
  url = "/bio/"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "https://scholar.google.com.au/citations?user=jYQfwwkAAAAJ"
  weight = 1

[taxonomies]
  tag = "tags"
  category = "categories"
