{\rtf1\ansi\ansicpg1252\cocoartf2822
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 name: Deploy Hugo site to GitHub Pages\
\
on:\
  push:\
    branches:\
      - main  # or your default branch\
\
jobs:\
  deploy:\
    runs-on: ubuntu-latest\
\
    steps:\
    - name: Checkout repo\
      uses: actions/checkout@v4\
\
    - name: Setup Hugo\
      uses: peaceiris/actions-hugo@v2\
      with:\
        hugo-version: '0.125.4'  # use whatever version you're using\
\
    - name: Build site\
      run: hugo --minify\
\
    - name: Deploy to GitHub Pages\
      uses: peaceiris/actions-gh-pages@v3\
      with:\
        github_token: $\{\{ secrets.GITHUB_TOKEN \}\}\
        publish_dir: ./public\
}